### ISSUE TITLE
Error after intallation

### ISSUE THREAD

**Issue by saturnxxi** [aimeos/aimeos-symfony#16]
After installing i receive the following error, if am trying to add one demo article to the basket:

_Compile Error: Declaration of Aimeos\MShop\Service\Provider\Decorator\Base::__construct(Aimeos\MShop\Service\Provider\Iface $provider, Aimeos\MShop\Context\Item\Iface $context, Aimeos\MShop\Service\Item\Iface $serviceItem) must be compatible with Aimeos\MShop\Service\Provider\Factory\Iface::__construct(Aimeos\MShop\Context\Item\Iface $context, Aimeos\MShop\Service\Item\Iface $serviceItem)_

Symfony 2.8.6, PHP 7.0.0

**Comment by aimeos** [comment]
PHP 7.0.0 is buggy. Please use at least PHP 7.0.4

**Comment by saturnxxi** [comment]
Thank you.
