### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by saturnxxi** [aimeos/aimeos-symfony#17]
I have many 404 errors, for example:

jsonadm/product?site=default (right after admin login or on the product details page)
checkout/delivery (prozess order)
basket/delete?b_position=0 (not possible to delete products from basket)

Am i missing something?

I think your [documentation](https://aimeos.org/docs/Symfony/Configure_FOSUserBundle_login) is not up  to date. There is no setting named *classes* under *aimeos_shop* according to your Configuration.php.

**Comment by aimeos** [comment]
You are right, the "classes" key has been removed and is now merged into the "mshop" key:
https://aimeos.org/docs/Symfony/Configure_FOSUserBundle_login

What did you've configured so far? If you set up the bundle according to the documentation, everything should work well: https://github.com/aimeos/aimeos-symfony#installation

**Comment by aimeos** [comment]
Which Aimeos version do you use? 2016.04.x or dev-master?

**Comment by saturnxxi** [comment]
I have added this line to my composer.json **"aimeos/aimeos-symfony": "~2016.04"** in order to install your bundle.

I have installed the shop bundle according to the documentation on github and configured the FosUserBundle.

**Comment by saturnxxi** [comment]
You are right, i have created new project and added both bundles yours and FosUserBundle. Configured them. All routes are found without errors.
