### ISSUE TITLE
Override Templates

### ISSUE THREAD

**Issue by saturnxxi** [aimeos/aimeos-symfony#18]
Hello,

i want to override existing templates. I have generated an extension with Aimeos Extension Builder. Where i have to put it, and how can i activate my extension? I put it in ext folder, but nothing happens.

btw. The link to the extension builder on this page https://aimeos.org/docs/Developers/Html_frontend/Overwrite_existing_templates is wrong.

Thank you.

**Comment by aimeos** [comment]
If the versions match (you need 2016.x I think) then it's enough to put the extension in the "ext" folder. If it contains implemented classes too, you might need to add them to the autoload section of your composer.json file.

Which template did you copy and where did you stored it?

**Comment by saturnxxi** [comment]
Yes, i need 2016.x. I have the following folder structure now:

![folder structure](http://i.imgur.com/vvDU455.png)

**Comment by aimeos** [comment]
The directory path must be exactly the same. Yours is missing the "catalog" part

**Comment by saturnxxi** [comment]
Oh, sorry, my mistake. Thank you.
