### ISSUE TITLE
Could not resolve composer requirements

### ISSUE THREAD

**Issue by pmarien** [aimeos/aimeos-symfony#20]
I have a fresh symfony environment (version 3.1).
When I was run "composer require "aimeos/aimeos-symfony" I got the following error:

> Your requirements could not be resolved to an installable set of packages.
> Problem 1
> - Installation request for aimeos/aimeos-symfony ^2016.07 -> satisfiable by aimeos/aimeos-symfony[2016.07.1].
> - aimeos/aimeos-symfony 2016.07.1 requires friendsofsymfony/user-bundle ~2.0@dev -> satisfiable by friendsofsymfony/user-bundle[2.0.x-dev, v2.0.0-alpha1, v2.0.0-alpha2, v2.0.0-alpha3] but these conflict with your requirements or minimum-stability.

This problem can be solved by requiring the dev version of the fos user bundle manually before, but this is not a production solution.

**Comment by aimeos** [comment]
Did you add these lines to your composer.json?
```
    "prefer-stable": true,
    "minimum-stability": "dev",
```
The foruser bundle is a problem of itself. There's no stable 2.0 version since two years and the 1.x versions doesn't work with Symfony 3

**Comment by pmarien** [comment]
Is the fos user bundle required? Would it be a possibility to use the symfony user interface where needed and let the user (developer) implement the login by him self?

**Comment by aimeos** [comment]
The Symfony User implementation is also possible and there's a User entity implementation included in the Aimeos Symfony bundle. The only thing is that the fosuser bundle is required in the Aimeos bundle, so it's installed regardless if you use it or not.
