### ISSUE TITLE
Order without address(es)

### ISSUE THREAD

**Issue by LaKrue** [aimeos/aimeos-symfony#21]
Hi guys,

I'm running a Sf3 based Aimeos shop with FOS user bundle integrated.

The Shop is accessible for authenticated fos users only and configured to use the onepage layout without addresses for invoicing and shipping.

My problem is, that the order has no associated addresses as no customer address actually exists.
Unfortunately, the order status notification job is only checking for emails in associated addresses.

So the log is raising error messages about every past order ... every minute:
> Error while trying to send payment e-mail for order ID "2743" and status "6": Address for domain "payment" not available

Did I miss something in the configuration or would "order without address" be a feature request?

My quick and dirty workaround will be to create an address with only an email on registration and assign it. I'm afraid I have to start hacking the address out of the customers order history and so on.

I can imagine it's not to much effort to fallback to the account email?

**Comment by aimeos** [comment]
Well, you've already proven that ordering without address is possible with Aimeos. But, if you want to send an order confirmation e-mail, you need a payment address in the order with at least the e-mail.

If all of your customers must log in first, you can use the "Autofill" basket plugin to add their address from the FOS user table automatically. That's only a configuration thing and doesn't require any implementation or hacking.

**Comment by LaKrue** [comment]
Thanks, that was faster than expected.

I tried some options, but missed the obvious one.

Awesome. Just starting the next shop project!

**Comment by aimeos** [comment]
Can we add your project to our showcase page?
