### ISSUE TITLE
Update of app/config/routing.yml via composer ScriptHandler task

### ISSUE THREAD

**Issue by LaKrue** [aimeos/aimeos-symfony#22]
Hi, in my opinion, forcing the aimeos_shop routing in app/config/routing.yml  via composer ScriptHandler is a uncomfortable choice against flexibility.

[https://github.com/aimeos/aimeos-symfony/blob/master/Composer/ScriptHandler.php#L218](url)

I'm using a custom routing to include user/session locales in the the url and have custom prefixes for account related, the core shop and admin related routes.

Currently, we git reset after deployment and manually reset the routing.yml in local dev repos after install/update. Inconvenient flow for lazy devs.

What do you think about removing this part?

**Comment by aimeos** [comment]
Maybe we can make it optional, so you can deactivate it?

**Comment by LaKrue** [comment]
That's ok for me. I would guess mosts projects that integrate aimeos seriously with symfony wouldn't mind to add the routing manually like most bundles handle require. I picture it as a rapid prototype / demo support like setup/default/demo.

Sorry for the dummy title "bla" btw. Updated it ...

**Comment by aimeos** [comment]
The easiest thing would be to split up the SciptHandler class and move the code that updates the routing and the config to a new class. Then, you can leave it out in your composer.json

**Comment by LaKrue** [comment]
Perfectly fine with me.

**Comment by aimeos** [comment]
Are you able to create a PR for that? We would merge that for sure :-)
