### ISSUE TITLE
Error for php bin/console aimeos:account "'siteid' cannot be null"

### ISSUE THREAD

**Issue by primus852** [aimeos/aimeos-symfony#24]
I am using `"aimeos/aimeos-symfony": "^2016.07"` and the `composer update` runs smoothly w/out any errors (including demo content)

When I try to create a new Admin account with `php bin/console aimeos:account xx@email.com` it produces a mysql error: `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'siteid' cannot be null`

The query is: 
`INSERT INTO mshop_customer (
  siteid, label, code, company, vatid, salutation, title,
  firstname, lastname, address1, address2, address3,
  postal, city, state, countryid, langid, telephone,
  email, telefax, website, birthday, status, vdate,
  password, mtime, editor, ctime
) VALUES (
  NULL,'xx@email.com','xx@email.com','','','','','','','','','','','','
  ',NULL,NULL,'','xx@email.com','','',NULL,0,NULL,'4f426ffebe55d9440332b94757e56b0a132e26c5','2016-09-20 16:44:34','aimeos:account','2016-09-20 16:44:34'
);`

Symfony Version is 3.1.4

Side question, is there an admin account which I can login to?

**Comment by aimeos** [comment]
You don't use the FosUser bundle, aren't you?
Can you add ", nullable=true" after "type=integer" in https://github.com/aimeos/aimeos-symfony/blob/master/Entity/User.php#L31 and try again?

**Comment by primus852** [comment]
Ok, I did that, and altered the table with `ALTER TABLE mshop_customer MODIFY siteid INT;` and it seems to work. And no, I am not using the FOSUserBundle (yet), only a fresh install of symfony and aimeos. Should I try again with FOSUser? Thank you anyway!

**Comment by primus852** [comment]
Update: tried again with fresh symfony and FOSUserBundle (with minimum UserClass) and got this upon 'Checking index "idx_fosus_langid"`: `Syntax error or access violation: 1072 Key column 'langid' doesn't exist in table`. Altered table to have langid (manually): `ALTER TABLE myDB_base.fos_user ADD langid INT;` but then there is the same message with `lastname`. Am I doing sth essentially wrong? What is the regular workflow?

**Comment by aimeos** [comment]
Thanks, we've modified the User entity accordingly.

Regarding the FosUser setup: It seems like the necessary columns haven't been added in your case. Did you've executed `app/console aimeos:setup` after installing the bundle?

**Comment by primus852** [comment]
Ok here ist what I do:

* Install fresh Symfony (3.1.4) with ``symfony new deav_aimeos && cd deav_aimeos && HTTPDUSER=`ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1` && setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var && setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX var` `` (for the permissions)
* Update my `parameters.yml` (dropped and created database acoordingly)
* Update my `security.yml` to the exact same as suggested.
* add `new Aimeos\ShopBundle\AimeosShopBundle(),` to `AppKernel.php`
* add the according lines to composer.json (See here http://pastebin.com/48rMP5Zs) --> changed to `master`
* run `composer update` (v1.2.1)
* Altered the `base.html.twig` template. --> `/list` works as intended (I see three articles and can browse them)
* run `php bin/console aimeos:account xx@emai.com --admin` --> ` 1048 Column 'siteid' cannot be null`

I checked that I have the correct version of `vendor/aimeos/aimeos-symfony/Entity\User.php` which I do.

Nevertheless I did the `ALTER TABLE mshop_customer MODIFY siteid INT;` again and could create an admin user. Going to `admin` and logging in with the new credentials lead to an error message (http://pastebin.com/vMRNrQAk) 

I tried it like 6 times already. Anything else I can try?

**Comment by aimeos** [comment]
OK, now I understand what you are trying.

Your setup is OK but you can't create new admin accounts with `php bin/console aimeos:account --admin <email>` at the moment because there are no defaults for authentication in Symfony but a lot of different options. Thus, the docs only contains an example for HTTP basic authentication and the "--admin" option is a bit misleading there (it was copied from the Laravel integration). You need to set up one of the options offered by Symfony for authenticating admin users if you want something different than HTTP basic auth.

The FosUserBundle is the most used option for the frontend (checked again that it's working in combination with ~2016.07) and if some columns are missing, you probably didn't executed `composer update` or the "post-update-cmd" doesn't contain the same lines as "post-install-cmd".

The default user "bundle" using the "mshop_customer" table isn't an option for most environments because you would have to implement user registration, password reset, etc. yourself. Nevertheless, it should be working to create accounts that are stored in this table. We had a look into the other integration and all allow NULL values for the siteid. Therefore, we will change the mshop_customer.siteid column to allow NULL in the future.

**Comment by aimeos** [comment]
The change has been added to dev-master. You can now create new >>user<< accounts using `php bin/console aimeos:account <email>` that are stored in the "mshop_customer" table

**Comment by primus852** [comment]
I finally got it to work, but NOT with "master", only with "^2016.07"
In the demo shop I made a "demo buy", and the user created I made an admin (because I don't know where else the user is entered in the database". With that user and an updated security.yml (using the FOSUserBundle" I managed to login to the admin area.
Not sure why it would not let me take the "master". I get a 404 for`/admin` and `/list`

Thank you anyway!

**Comment by aimeos** [comment]
Can you post your security.yml file? That might be a great good reference.

**Comment by aimeos** [comment]
Have you tried `http://127.0.0.1:8000/app.php/list` in combination with dev-master instead of `http://127.0.0.1:8000/list`?

**Comment by aimeos** [comment]
The full code for the App\Providers\AuthServiceProvider in Laravel 5.2 is
```
<?php

namespace App\Providers;

use Illuminate\Contracts\Auth\Access\Gate as GateContract;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any application authentication / authorization services.
     *
     * @param  \Illuminate\Contracts\Auth\Access\Gate  $gate
     * @return void
     */
    public function boot(GateContract $gate)
    {
        $this->registerPolicies($gate);

        $gate->define('admin', function($user, $roles) {
            return app( '\Aimeos\Shop\Base\Support' )->checkGroup( $user->id, $roles );
        });
    }
}
```
