### ISSUE TITLE
Installing under Symfony Standard 3.2.*

### ISSUE THREAD

**Issue by Sentence** [aimeos/aimeos-symfony#25]
Need to downgrade the `"symfony/monolog-bundle": "^3.0"` to `"symfony/monolog-bundle": "^2.0"` for succss `composer update`.

It works fine now, but lack of doc. :)

My original composer.json file:

`{`
`    "name": "symfony/framework-standard-edition",`
`    "license": "MIT",`
`    "type": "project",`
`    "description": "The \"Symfony Standard Edition\" distribution",`
`    "autoload": {`
`        "psr-4": { "": "src/" },`
`        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]`
`    },`
`    "autoload-dev": {`
`        "psr-4": { "Tests\\": "tests/" }`
`    },`
`    "require": {`
`        "php": ">=5.5.9",`
`        "symfony/symfony": "3.2.*",`
`        "doctrine/orm": "^2.5",`
`        "doctrine/doctrine-bundle": "^1.6",`
`        "doctrine/doctrine-cache-bundle": "^1.2",`
`        "symfony/swiftmailer-bundle": "^2.3",`
`        "symfony/monolog-bundle": "^3.0",`
`        "symfony/polyfill-apcu": "^1.0",`
`        "sensio/distribution-bundle": "^5.0",`
`        "sensio/framework-extra-bundle": "^3.0.2",`
`        "incenteev/composer-parameter-handler": "^2.0",`
`		"aimeos/aimeos-symfony": "~2016.10"`
`    },`
`    "require-dev": {`
`        "sensio/generator-bundle": "^3.0",`
`        "symfony/phpunit-bridge": "^3.0"`
`    },`
`	"prefer-stable": true,`
`    "minimum-stability": "dev",`
`    "scripts": {`
`        "symfony-scripts": [`
`            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",`
`            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",`
`            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",`
`            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",`
`            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",`
`            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"`
`        ],`
`        "post-install-cmd": [`
`			"Aimeos\\ShopBundle\\Composer\\ScriptHandler::installBundle",`
`            "Aimeos\\ShopBundle\\Composer\\ScriptHandler::updateConfig",`
`            "Aimeos\\ShopBundle\\Composer\\ScriptHandler::setupDatabase",`
`            "@symfony-scripts"`
`        ],`
`        "post-update-cmd": [`
`			"Aimeos\\ShopBundle\\Composer\\ScriptHandler::installBundle",`
`            "Aimeos\\ShopBundle\\Composer\\ScriptHandler::updateConfig",`
`            "Aimeos\\ShopBundle\\Composer\\ScriptHandler::setupDatabase",`
`            "@symfony-scripts"`
`        ]`
`    },`
`    "config": {`
`        "platform": {`
`            "php": "5.5.9"`
`        }`
`    },`
`    "extra": {`
`        "symfony-app-dir": "app",`
`        "symfony-bin-dir": "bin",`
`        "symfony-var-dir": "var",`
`        "symfony-web-dir": "web",`
`        "symfony-tests-dir": "tests",`
`        "symfony-assets-install": "relative",`
`        "incenteev-parameters": {`
`            "file": "app/config/parameters.yml"`
`        },`
`        "branch-alias": {`
`            "dev-master": "3.2-dev"`
`        }`
`    }`
`}`

**Comment by aimeos** [comment]
What was the problem why a downgrade was required?

**Comment by aimeos** [comment]
We've added symfony/monolog-bundle ~3.0 as supported version in our composer.json in dev-master. Now it should work out of the box. Can you confirm that?

**Comment by Sentence** [comment]
Sorry for this huge delay.

Now can install/update only with `^2.0` option, got this message with `^3.0`:

`  Problem 1`
`    - aimeos/aimeos-symfony 2016.10.1 requires symfony/monolog-bundle ~2.4 -> satisfiable by symfony/monolog-bundle[2.x-dev].`
`    - aimeos/aimeos-symfony 2016.10.2 requires symfony/monolog-bundle ~2.4 -> satisfiable by symfony/monolog-bundle[2.x-dev].`
`    - aimeos/aimeos-symfony 2016.10.x-dev requires symfony/monolog-bundle ~2.4 -> satisfiable by symfony/monolog-bundle[2.x-dev].`
`    - Conclusion: don't install symfony/monolog-bundle 2.x-dev`
`    - Installation request for aimeos/aimeos-symfony ~2016.10 -> satisfiable by aimeos/aimeos-symfony[2016.10.1, 2016.10.2, 2016.10.x-dev].`

**Comment by aimeos** [comment]
Did you use "aimeos/aimeos-symfony": "dev-master" in your composer.json?

**Comment by Sentence** [comment]
My reference `composer.json` is in the issue starting comment, so you can check everything from it.

Used `"aimeos/aimeos-symfony": "~2016.10",`, swapped to `dev-master` and now **works fine**, **thanks**.

Can you create a block about Symfony 3 installation? (For further usage. :))

Can close this issue, thank you again.

**Comment by aimeos** [comment]
Even better: We've changed that in the 2016.10 branch as well and released a new version. Now you can use the latest Symfony release without the need to change anything.
