### ISSUE TITLE
Failed product image upload

### ISSUE THREAD

**Issue by mgwebgroup** [aimeos/aimeos-symfony#26]
I have installed aimeos and FOSUser bundles per instructions on github. When using extadm interface, I cannot upload images. This error comes up: "Could not upload file. Please notify your administrator".
The image files upload into web/preview and web/files directories. However browser log appears to have incorrect path of the image: "127.0.0.1:58146 [404]: /.preview/b/1/b120dcfbdfed16b41cefb08ae4d999dd.jpg - No such file or directory". There is "dot" in the path to the file. How to get rid of it?
So far the following measures did not work:
* Changed file permissions on web/files, web/preview, web/uploads recursively to 777
* Upgraded composer.json to require: { ""aimeos/aimeos-symfony": "dev-master" }, ran composer update. (another error came up about not being able clear the Aimeos cache for the site: " Call to undefined method Aimeos\MW\Cache\None::flush() in /home/alex/Documents/110318 MGWebGroup/02. Projects/161114_nataly-health/03_active_version/vendor/aimeos/aimeos-symfony/Command/CacheCommand.php on line 62")

**Comment by aimeos** [comment]
Can you try these two configurations:
```
aimeos_shop:
    uploaddir: /
```
or
```
aimeos_shop:
    uploaddir: /./
```

The dev-master branch wasn't aligned to the latest changes in the Aimeos core yet. This should be fixed now.

**Comment by mgwebgroup** [comment]
First option fixed the issue. Thanks!
