### ISSUE TITLE
Integration with MercadoPago

### ISSUE THREAD

**Issue by alanrivetta** [aimeos/aimeos-symfony#27]
Hello!

I would like to know how to integrate the payment platform MercadoPago.

Is there any way?

**Comment by aimeos** [comment]
The preferred way is to install the Omnipay extension for MercadoPago (https://github.com/victorximenis/omnipay-mercadopago) and the Aimeos ai-payments extension (https://github.com/aimeoscom/ai-payments). Maybe there are some fixes in the MercadoPago extension necessary if it doesn't already confirm 100% to the Omnipay standards.

**Comment by alanrivetta** [comment]
Thank you very much for the recommendation!
