### ISSUE TITLE
configuration interface admin Symfony

### ISSUE THREAD

**Issue by hamzarebaichkaw** [aimeos/aimeos-symfony#28]
Symfony\Component\Security\Core\Exception\BadCredentialsException: Bad credentials. in C:\wamp64\www\Aircursh\vendor\symfony\symfony\src\Symfony\Component\Security\Core\Authentication\Provider\UserAuthenticationProvider.php:73 Stack trace: #0 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(3369): session_start() #1 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(3435): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #2 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(3203): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #3 C:\wamp64\www\Aircursh\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ContextListener.php(83): Symfony\Component\HttpFoundation\Session\Session->get('_security_aimeo...') #4 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(5057): Symfony\Component\Security\Http\Firewall\ContextListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #6 C:\wamp64\www\Aircursh\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.php(106): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #8 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(2936): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #9 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(2851): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #10 C:\wamp64\www\Aircursh\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher.php(136): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #11 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(4286): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #12 C:\wamp64\www\Aircursh\var\cache\dev\classes.php(4256): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #13 C:\wamp64\www\Aircursh\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(168): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #14 C:\wamp64\www\Aircursh\web\app_dev.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #15 {main}

**Comment by aimeos** [comment]
You've used the wrong username and password. If you copied the content for your `security.yml` from https://github.com/aimeos/aimeos-symfony#admin, the credentials are `admin` and `secret`
