### ISSUE TITLE
Bundle version restriction

### ISSUE THREAD

**Issue by Laurent3170** [aimeos/aimeos-symfony#31]
Trying to find a bundle that can be separated in parts (basket, button to pay, checkout, etc.), meaning not a global system like PrestaShop or other, and that can be easily overrided. It seems that aimeos can do this, but, in the [composer.json](https://github.com/aimeos/aimeos-symfony/blob/master/composer.json), there are restrictions about version for bundles that make no possibility to use with newer versions, i.e. Symfony 3.3.9 and Swiftmailer 3.*. is it intentional?
```
"symfony/symfony": "~2.4||~3.0",
"symfony/swiftmailer-bundle": "~2.3",
```
Thanks

**Comment by aimeos** [comment]
~3.0 covers all Symfony 3.x versions from 3.0.0 to 3.99.99.
We will check if the swiftmailer bundle 3.x works as well and update the composer.json. Thanks for that hint!

**Comment by Laurent3170** [comment]
Thanks.
Wasn't sure with the covering of `~3.0`.

**Comment by Laurent3170** [comment]
swiftmailer bundle 3.x implies use of swiftmailer 6 that has some changes.

**Comment by aimeos** [comment]
The swiftmailer bundle 3.0 seems to work well. We've updated the composer.json in the dev-master branch. Thanks again!

**Comment by Laurent3170** [comment]
Thanks for the news. I'll test it
