### ISSUE TITLE
Error Item with ID "" in "media.id" not found

### ISSUE THREAD

**Issue by GalinaBublik** [aimeos/aimeos-symfony#32]
Can't upload image to product((

**Comment by aimeos** [comment]
Which Aimeos, Symfony and PHP versions are you using?
The latest 2017.10 version seems to work pretty well.

**Comment by GalinaBublik** [comment]
"symfony/symfony": "3.2.*",
"aimeos/aimeos-symfony2": "~2017.04"
PHP Version 5.6.29
Do I need to update?

**Comment by aimeos** [comment]
Please use "aimeos/aimeos-symfony": "~2017.10".
The version you are using isn't supported any more.

**Comment by GalinaBublik** [comment]
Removing aimeos/aimeos-symfony2 (2017.10.1)
Installing aimeos/aimeos-symfony (2017.10.1)
Updating symfony/symfony (v3.2.13 => v3.3.12)
Currently work fine - Thank you!
