### ISSUE TITLE
can it be use with sonata admin bundle ?

### ISSUE THREAD

**Issue by maavia10** [aimeos/aimeos-symfony#33]
i have build a coomplete app with sonata admin bundle 
now client require for a shop module 
can you please let me know how i can integrate it with sonata admin bundle 
and one more can i extend its entity classes?

**Comment by aimeos** [comment]
We haven't have any experience with Sonata but the Aimeos admin interface is built for being integrated into existing applications. You can give it a try.

The entity classes can be extended in the Symfony standard way:
https://github.com/aimeos/aimeos-symfony/tree/master/Entity
