### ISSUE TITLE
Compatibility with Symfony4

### ISSUE THREAD

**Issue by GerkinDev** [aimeos/aimeos-symfony#34]
Hi, I'm willing to install this bundle for a Symfony 4 project, but I'm wondering if both are compatible. Why the plugin does not includes symfony v 4.x.x as allowed dependency?

Cheers

**Comment by aimeos** [comment]
Symfony 4 was released six weeks after Aimeos 2017.10 so the necessary changes were only in 2018.01 up to now. We've backported them and released 2017.10.3 with Symfony 4.0 support now.

Thanks for mentioning!
