### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by OuterAlt** [aimeos/aimeos-symfony#36]
Hi,
I'm trying to install Aimeos (not from scratch, on an already existing app), following the instructions in the installation part, but when running `composer update` i got this error : 

```
An exception occurred while executing 'SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode
  ='ANSI'':

  SQLSTATE[42601]: Syntax error: 7 ERREUR:  ne peut pas insérer les commandes multiples dans une instruction préparée
```

Does anyone know how to fix this ?
Thanks

**Comment by aimeos** [comment]
Which database and version are you using?

**Comment by aimeos** [comment]
Seems like you are using PostgreSQL without the required database specific settings:
https://aimeos.org/docs/Developers/Library/Database_support
