### ISSUE TITLE
  [ErrorException]   Undefined index: symfony-app-dir after composer update/install

### ISSUE THREAD

**Issue by felipep** [aimeos/aimeos-symfony#37]
I have a symfony 4.1.3 installation with aimeos 2018.07, after installing everything the composer command cannot finish, I got the error `  [ErrorException]
  Undefined index: symfony-app-dir`
also there were problems regarding parameters like database_host, database_user, database_port, database_password, which in symfony 4.3 are not included anymore, I just declared them to avoid a problem.

**Comment by aimeos** [comment]
Has been fixed in dev-master and in the new 2018.10 release
