### ISSUE TITLE
Improve read.md for installation with symfony 4

### ISSUE THREAD

**Issue by felipep** [aimeos/aimeos-symfony#38]
The current documentation only shows how to use this project with symfony 3 for symfony 4 there are a lot of differences.

**Comment by aimeos** [comment]
Yes, that's true and we want to offer documentation for Symfony 4 as well. Do you want to help?

**Comment by felipep** [comment]
I would be glad to help writing the documentation, how can we coordinate that?

**Comment by aimeos** [comment]
At least for the installation section we need two sub-sections, one for Symfony 3 and one for Symfony 4 because they are so different. You can create a pull request with the Symfony 4 section and we will check and improve that together with you :-)

**Comment by aimeos** [comment]
Documentation has been updated for Symfony 4
