### ISSUE TITLE
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by benjaminzhou01** [aimeos/aimeos-symfony#39]
http://127.0.0.1:8000/list

An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
Exceptions 3 Logs 1 Stack Traces 3
Doctrine\DBAL\Exception\
ConnectionException
in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php (line 113)
in vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php->convertException (line 184)
in vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php::wrapException (line 169)
in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php::driverException (line 47)

**Comment by aimeos** [comment]
Seems to be a misconfiguration of your MySQL server or the database doesn't exist
