### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by carlofraue79** [aimeos/aimeos-symfony#40]
There are more errors of documentation i have executed the step manually and the result it is ? 

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FOSUserBundle" from namespace "FOS\UserBundle".
Did you forget a "use" statement for another namespace? in /vagrant/myshop/src/Kernel.php:33
Stack trace:
#0 /vagrant/myshop/vendor/symfony/http-kernel/Kernel.php(405): App\Kernel->registerBundles()
#1 /vagrant/myshop/vendor/symfony/http-kernel/Kernel.php(120): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /vagrant/myshop/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
#3 /vagrant/myshop/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /vagrant/myshop/bin/console(40): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /vagrant/myshop/src/Kernel.php on line 33
vagrant@demo:/vagrant/myshop$ php bin/console list
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AimeosShopBundle" from namespace "Aimeos\ShopBundle".
Did you forget a "use" statement for another namespace? in /vagrant/myshop/src/Kernel.php:33
Stack trace:
#0 /vagrant/myshop/vendor/symfony/http-kernel/Kernel.php(405): App\Kernel->registerBundles()
#1 /vagrant/myshop/vendor/symfony/http-kernel/Kernel.php(120): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /vagrant/myshop/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
#3 /vagrant/myshop/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /vagrant/myshop/bin/console(40): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /vagrant/myshop/src/Kernel.php on line 33

**Comment by aimeos** [comment]
Can you post the output of `composer show`?

**Comment by carlofraue79** [comment]
@aimeos the output is the following 
composer show
doctrine/annotations                v1.6.0  Docblock Annotations Parser
doctrine/cache                      v1.8.0  Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.5.0  Collections Abstraction library
doctrine/common                     v2.10.0 PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend ...
doctrine/dbal                       v2.8.0  Database Abstraction Layer
doctrine/doctrine-bundle            1.9.1   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5   Symfony Bundle for Doctrine Cache
doctrine/doctrine-migrations-bundle v1.3.1  Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0  Doctrine Event Manager component
doctrine/inflector                  v1.3.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.1.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.8.1  Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.6.3  Object-Relational-Mapper for PHP
doctrine/persistence                v1.1.0  The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object ...
doctrine/reflection                 v1.0.0  Doctrine Reflection component
easycorp/easy-log-handler           v1.0.7  A handler for Monolog that optimizes log messages to be processed by humans instead of software. Improve your produc...
egulias/email-validator             2.1.6   A library for validating emails against several RFCs
facebook/webdriver                  1.6.0   A PHP client for Selenium WebDriver
fig/link-util                       1.0.0   Common utility implementations for HTTP links
jdorn/sql-formatter                 v1.2.17 a PHP SQL highlighting library
monolog/monolog                     1.24.0  Sends your logs to files, sockets, inboxes, databases and various web services
nikic/php-parser                    v4.1.0  A PHP parser written in PHP
ocramius/package-versions           1.3.0   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.1.1   A library providing utilities to generate, instantiate and generally operate with Object Proxies
phpdocumentor/reflection-common     1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information t...
phpdocumentor/type-resolver         0.4.0
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/link                            1.0.0   Common interfaces for HTTP links
psr/log                             1.1.0   Common interface for logging libraries
psr/simple-cache                    1.0.1   Common interfaces for simple caching
sensio/framework-extra-bundle       v5.2.2  This bundle provides a way to configure your controllers with annotations
swiftmailer/swiftmailer             v6.1.3  Swiftmailer, free feature-rich PHP mailer
symfony/asset                       v4.2.0  Symfony Asset Component
symfony/browser-kit                 v4.2.0  Symfony BrowserKit Component
symfony/cache                       v4.2.0  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                      v4.2.0  Symfony Config Component
symfony/console                     v4.2.0  Symfony Console Component
symfony/contracts                   v1.0.0  A set of abstractions extracted out of the Symfony components
symfony/css-selector                v4.2.0  Symfony CssSelector Component
symfony/debug                       v4.2.0  Symfony Debug Component
symfony/debug-bundle                v4.2.0  Symfony DebugBundle
symfony/debug-pack                  v1.0.6  A debug pack for Symfony projects
symfony/dependency-injection        v4.2.0  Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.2.0  Symfony Doctrine Bridge
symfony/dom-crawler                 v4.2.0  Symfony DomCrawler Component
symfony/dotenv                      v4.2.0  Registers environment variables from a .env file
symfony/event-dispatcher            v4.2.0  Symfony EventDispatcher Component
symfony/expression-language         v4.2.0  Symfony ExpressionLanguage Component
symfony/filesystem                  v4.2.0  Symfony Filesystem Component
symfony/finder                      v4.2.0  Symfony Finder Component
symfony/flex                        v1.1.8  Composer plugin for Symfony
symfony/form                        v4.2.0  Symfony Form Component
symfony/framework-bundle            v4.2.0  Symfony FrameworkBundle
symfony/http-foundation             v4.2.0  Symfony HttpFoundation Component
symfony/http-kernel                 v4.2.0  Symfony HttpKernel Component
symfony/inflector                   v4.2.0  Symfony Inflector Component
symfony/intl                        v4.2.0  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle                v1.9.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about wri...
symfony/monolog-bridge              v4.2.0  Symfony Monolog Bridge
symfony/monolog-bundle              v3.3.1  Symfony MonologBundle
symfony/options-resolver            v4.2.0  Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.5  A pack for the Doctrine ORM
symfony/panther                     v0.2.0  A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge              v4.2.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu           v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring           v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                     v4.2.0  Symfony Process Component
symfony/profiler-pack               v1.0.3  A pack for the Symfony web profiler
symfony/property-access             v4.2.0  Symfony PropertyAccess Component
symfony/property-info               v4.2.0  Symfony Property Info Component
symfony/routing                     v4.2.0  Symfony Routing Component
symfony/security-bundle             v4.2.0  Symfony SecurityBundle
symfony/security-core               v4.2.0  Symfony Security Component - Core Library
symfony/security-csrf               v4.2.0  Symfony Security Component - CSRF Library
symfony/security-guard              v4.2.0  Symfony Security Component - Guard
symfony/security-http               v4.2.0  Symfony Security Component - HTTP Integration
symfony/serializer                  v4.2.0  Symfony Serializer Component
symfony/serializer-pack             v1.0.1  A pack for the Symfony serializer
symfony/stopwatch                   v4.2.0  Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.4  Symfony SwiftmailerBundle
symfony/test-pack                   v1.0.4  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                 v4.2.0  Symfony Translation Component
symfony/twig-bridge                 v4.2.0  Symfony Twig Bridge
symfony/twig-bundle                 v4.2.0  Symfony TwigBundle
symfony/validator                   v4.2.0  Symfony Validator Component
symfony/var-dumper                  v4.2.0  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                v4.2.0  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                    v4.2.0  Symfony WebLink Component
symfony/web-profiler-bundle         v4.2.0  Symfony WebProfilerBundle
symfony/web-server-bundle           v4.2.0  Symfony WebServerBundle
symfony/yaml                        v4.2.0  Symfony Yaml Component
twig/twig                           v2.5.0  Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                    1.3.0   Assertions to validate method input/output with nice error messages.
zendframework/zend-code             3.3.1   provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application

**Comment by aimeos** [comment]
There are no Aimeos packages installed at all. Did you remove them by your last `composer update` and the composer cache is still containing reference?

**Comment by carlofraue79** [comment]
i haven't remove any references to aimeos package.

**Comment by aimeos** [comment]
You don't have FosUserBundle installed either which causes the error. Please redo the steps from the readme to install Aimeos and the FosUserBundle: https://github.com/aimeos/aimeos-symfony

**Comment by VDev-S** [comment]
doesn't work for me to, same problem with FOS ..
