### ISSUE TITLE
You have requested a non-existent service "aimeos_page".

### ISSUE THREAD

**Issue by deankinns** [aimeos/aimeos-symfony#42]
Attempting to follow the doccumetation (https://aimeos.org/docs/Symfony/Create_new_pages) to make a new page and i get this error. 

Not only that but also a search through the code does not find the "aimeos_page" or "getSections". Is this part of the documentation out of date or am i just missing something?

**Comment by aimeos** [comment]
Thanks for the hint, it was out of date and now contains working code
