### ISSUE TITLE
Override existing templates twig

### ISSUE THREAD

**Issue by abodje** [aimeos/aimeos-symfony#44]
**Hello,
 i want to Overriding  twig layout  file Symfony (Aimeos Symfony Bundle) i have symfony 3.4 

thank**

**Comment by aimeos** [comment]
Which one exactly?

**Comment by abodje** [comment]
i want to customize the template( frontend )

**Comment by aimeos** [comment]
Aimeos consists of a lot of templates for the frontend:
https://github.com/aimeos/ai-client-html/tree/master/client/html/templates

Here's an article how to adapt the frontend:
https://aimeos.org/docs/Developers#HTML_clients

**Comment by abodje** [comment]
thank Aimeos but  I want to personalize by adding my own template with my own theme by putting the elements of the view in the template / views

**Comment by aimeos** [comment]
Moved to https://aimeos.org/help/post10177.html
