### ISSUE TITLE
Exception in Controller/Frontend/Basket/Standard::addAddress caused by a deserialization in Customer/Manager/FosUser::createItemBase

### ISSUE THREAD

**Issue by lgeorget** [aimeos/aimeos-symfony#47]
Hello Aimeos developers,

first of all thank you for aimeos-core and aimeos-symfony. We've started using it and we're really impressed by the overall design and range of functionality.

I have tracked down a bug/incompatibility between the FosUser extension (installed with aimeos-symfony) and the Basket controller. More precisely, the problem occur when a customer modifies its current address during the checkout process and click Save. The controller then fetches the address from the customer object via the getPaymentAddress() method, updates it with the information submitted by the user in the form and saves it again (https://github.com/aimeos/ai-client-html/blob/master/client/html/src/Client/Html/Checkout/Standard/Address/Billing/Standard.php#L601).

At the end of the process, the method addAddress() of the Basket controller is called (https://github.com/aimeos/ai-controller-frontend/blob/master/controller/frontend/src/Controller/Frontend/Basket/Standard.php#L365).  In this method, to thwart any XSS attempt, the strip_tags() function is called on all values in the array passed as argument.

The problem is that this array contains the key "roles" whose value is an array in case of FosUser. This value is stored as a string in the database but is deserialized as an array in method createItemBase() of the FosUser manager (https://github.com/aimeos/ai-fosuser/blob/master/lib/custom/src/MShop/Customer/Manager/FosUser.php#L638).

Calling strip_tags() on this value throws an exception since it's an array and the entire process results in a "A non-recoverable error occured" message on the website.

So, I don't know whether we should treat this is a bug from the ai-fosuser extension or from the ai-controller-frontend extension but in any case, there's an incompatibility between them. I think a way forward would be to move the call to strip_tags() from Controller/Frontend/Basket/Standard.php::addAddress() to Client/Html/Checkout/Standard/Address/Billing/Standard.php::setAddress()  to call strip_tags() only on fields originating from the HTML form.

What is your opinion on the matter?

**Comment by lgeorget** [comment]
By the way, I think I've opened this issue in the wrong repository. Sorry about that.

**Comment by aimeos** [comment]
Thank you very much for the detailed explaination. We would be glad if all bug reports would be like that :-)

The reason why strip_tags() is called in the frontend controller is that this should not only eleminate the rist of XSS for the HTML frontend but also for the JSON REST API. Therefore, the best way to solve this would be to check with is_string() if the value is a string before applying strip_tags() to it.

Can you create a PR in the aimeos/ai-controller-frontend repo?

**Comment by lgeorget** [comment]
Sure! Here it is: https://github.com/aimeos/ai-controller-frontend/pull/10

Thank you

**Comment by aimeos** [comment]
Also ported back to 2019.10 and a new release tagged (2019.10.9)
