### ISSUE TITLE
Do you support php 7.4 ?

### ISSUE THREAD

**Issue by hipachka** [aimeos/aimeos-symfony#48]
At now aimeos support 7.4 ??? And how can i solve it if not. How much fixes require for it? Most interested admin part not front. Thanks

**Comment by aimeos** [comment]
2020.01 is beta and should be only use for testing. 2019.10 should work but we are currently investigating if it does.

**Comment by aimeos** [comment]
PHP 7.4 works without problems with Symfony 3.4 and 4.4. Only 4.0/4.1 won't work due to PHP deprecation notices

**Comment by hipachka** [comment]
Sounds good. Okay, thank you! I will continue to test version 2019 with 4.4.* And I will make a new detail issue if I find something work wrong
