### ISSUE TITLE
error in installation: Aimeos\ShopBundle\Command\Command::getSiteItems()

### ISSUE THREAD

**Issue by stephanie-louis** [aimeos/aimeos-symfony#50]
launching composer update in the final step of the installation, i have this error

> 
Return value of Aimeos\ShopBundle\Command\Command::getSiteItems() must be of the type array, object returned

just after the step :
Update FOS user lists "key" columns                                   
  Checking table fos_user_list      OK

so the next message is 
Script Aimeos\ShopBundle\Composer\ScriptHandler::setupDatabase handling the post-update-cmd event terminated with an exception

I don't know if I can use the shop or if some tables are missing and then i'll get some bugs.
I can log in admin and the BO seems to work well.
I haven't test the integration in Front end.

Thanks for the help
Stéphanie

**Comment by aimeos** [comment]
Which Aimeos version are you using? 2019.10 is stable, 2020.01 is beta

**Comment by stephanie-louis** [comment]
Hi, 
my bad... Thank you for the help and fast answer !
