### ISSUE TITLE
error in Doctrine\UserManager::__construct() in new installation

### ISSUE THREAD

**Issue by gentooza** [aimeos/aimeos-symfony#52]
Hi again!

Please could you help me with what is wrong in my installation?
I think it's totally fresh, following the steps provided for symfony 4  and everything updated. But when I go to http://127.0.0.1:8000/ or http://127.0.0.1:8000/shop I get this exception:
```
Argument 3 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given, called in /home/joa/dev/sumak/sumak/var/cache/dev/ContainerJO6Yt8E/srcApp_KernelDevDebugContainer.php on line 1426
```
Something missconfigured in doctrine? or fos_user?

thanks and sorry!

**Comment by gentooza** [comment]
ok!

I've downgrade doctrine/orm from ^2.7 to
"doctrine/orm": "2.6.*",
in my composer.json

and now it works
is it ok?

**Comment by aimeos** [comment]
Yes, that should be OK

**Comment by gentooza** [comment]
thanks!
closing
