### ISSUE TITLE
[Solved] No item found for conditions: Array ( [locale.site.code] => default )

### ISSUE THREAD

**Issue by landNull** [aimeos/aimeos-symfony#57]
Followed installation instructions here on Github
/shop page loaded just fine

Added a custom logo, favicon, and filled in all of the fields on the settings page
Saved 
/shop throws the following error 
`No item found for conditions: Array
(
[locale.site.code] => default
)`

Did some research and found several people having the same issue with aimeos-Typo3 
"
Your MySQL database version doesn't support long indexes required for utf8mb4
"
Is this also the case for aimeos-symfony?

**Comment by aimeos** [comment]
If you use a MySQL version before MySQL 5.7.8 or MariaDB before MariaDB 10.2.2, the problem applies to all integrations including the Symfony bundle.

**Comment by landNull** [comment]
Thank you for the prompt response 
Server is running MariaDB 10.3.31
So I'll be digging into this in the next couple days. :)

**Comment by landNull** [comment]
Thank you for the prompt response
OS: Debian 10
Mariadb: 10.3.31

Maridb server ,cnf was already set to use utf8mb4 before I installed Aimeos.  
/etc/mysql/mariadb.conf.d/50-server.cnf
> # line 104: confirm default charaset
> # if use 4 bytes UTF-8, specify [utf8mb4]
> character-set-server  = utf8mb4
> collation-server      = utf8mb4_general_ci

I edited 50-server.cnf 
> collation-server      = utf8mb4_general_ci
to
> collation-server      = utf8mb4_unicode_ci

I'm going to drop the database then run **symfony update** then see what happens.

**Comment by landNull** [comment]
Recreated aimeos databas ran composer update and got this. 
I left all of the configurations in place that were made after running **composer update** and received the following error.

```
Script Aimeos\ShopBundle\Composer\ScriptHandler::setupDatabase handling the post-update-cmd event terminated with an exception
In DBAL.php line 113:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for u  
  ser 'aimeos'@'localhost' (using password: YES) 
                                                     
  [RuntimeException]                                 
  An error occurred when executing the "''\''aimeos  
  :setup'\'''" command 
```
I'm going to undo configurations up to **composer update** and see what happens then.

**Comment by aimeos** [comment]
The entered user name and password doesn't match the credentials you can log into the DB.

**Comment by landNull** [comment]
> The entered user name and password doesn't match the credentials you can log into the DB.

Well that's embarrassing.. that'll teach me to copy paste and run to my next task. :p

**Comment by landNull** [comment]
So I updated the user password *blush
I did not back track any of configuration yet as I wanted to see if dropping the database and running **composer update** would do the trick.
So...
the /shop is back up
But when I login at /admin the security credentials 
`Symfony\Component\Security\Core\Exception\BadCredentialsException: Bad credentials. in /var/www/html/aimeos/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:69 Stack trace: #0`  
I will backtrack configuration then see what happens. ;)

**Full error** 
`Symfony\Component\Security\Core\Exception\BadCredentialsException: Bad credentials. in /var/www/html/aimeos/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:69 Stack trace: #0 /var/www/html/aimeos/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(156): session_start() #1 /var/www/html/aimeos/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(323): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #2 /var/www/html/aimeos/vendor/symfony/http-foundation/Session/Session.php(251): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #3 /var/www/html/aimeos/vendor/symfony/http-foundation/Session/Session.php(273): Symfony\Component\HttpFoundation\Session\Session->getBag('attributes') #4 /var/www/html/aimeos/vendor/symfony/http-foundation/Session/Session.php(73): Symfony\Component\HttpFoundation\Session\Session->getAttributeBag() #5 /var/www/html/aimeos/vendor/symfony/security-http/Firewall/ContextListener.php(119): Symfony\Component\HttpFoundation\Session\Session->get('_security_aimeo...') #6 /var/www/html/aimeos/vendor/symfony/security-bundle/Debug/WrappedLazyListener.php(49): Symfony\Component\Security\Http\Firewall\ContextListener->authenticate(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #7 /var/www/html/aimeos/vendor/symfony/security-http/Firewall/AbstractListener.php(27): Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->authenticate(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #8 /var/www/html/aimeos/vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php(62): Symfony\Component\Security\Http\Firewall\AbstractListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #9 /var/www/html/aimeos/vendor/symfony/security-http/Firewall.php(98): Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners(Object(Symfony\Component\HttpKernel\Event\RequestEvent), Object(Generator)) #10 /var/www/html/aimeos/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #11 /var/www/html/aimeos/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher)) #12 /var/www/html/aimeos/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #13 /var/www/html/aimeos/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent)) #14 /var/www/html/aimeos/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request') #15 /var/www/html/aimeos/vendor/symfony/http-kernel/HttpKernel.php(134): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request') #16 /var/www/html/aimeos/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #17 /var/www/html/aimeos/vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/www/html/aimeos/public/index.php(25): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #19 {main}`

**Comment by aimeos** [comment]
Make sure you've added the security.yaml exactly as in the docs:
https://github.com/aimeos/aimeos-symfony#login-and-admin

Afterwards, use the `./bin/console` command described at the end of the section to create a new admin account and use the credentials entered there to log in.

**Comment by landNull** [comment]
Ok, finally had time to pursue this. :)
I re-followed the instructions you linked to and the admin login was back up and running.
I logged in went straight to the settings page.
I uploaded a site logo & site image (favicon). Both are .png files.
Changed the Shop name, Shop email & set the Shop domain.
Clicked on save, loaded /shop and received the same error.

![aimeosErrorAfterSavingShopSettings](https://user-images.githubusercontent.com/61285223/147699574-87b0f30e-0c30-4e38-b684-3472da29094c.png)

**Comment by landNull** [comment]
Worth noting:  The settings page layout was different after changing the database from
```
collation-server = utf8mb4_general_ci
to
collation-server = utf8mb4_unicode_ci
```
and re-configuring. 

So, we have determined, changing the collation-server settings for Mariadb does not resolve the error after saving the settings.

**Comment by aimeos** [comment]
Did you add the composer scripts and ran "composer up" afterwards?
https://github.com/aimeos/aimeos-symfony#composer

The records in the mshop_locale_site table are missing, either because the database setup didn't complete successfully or the command hasn't been executed.

**Comment by landNull** [comment]
Re-ran composer update
received errors about duplicate database tables.

Loaded /shop and there it is in all it's glory! :dancers:
