### ISSUE TITLE
Support for Symfony 5.4 LTS

### ISSUE THREAD

**Issue by vjandrea** [aimeos/aimeos-symfony#63]
Is this package still developed ? I can't find a contribution guide or a roadmap.
I'd like to know if Symfony 5.4 support is planned.

Thanks.

**Comment by aimeos** [comment]
We want to switch to Symfony 6 directly

**Comment by BobMali** [comment]
> We want to switch to Symfony 6 directly

And is there a possible RC or some kind of roadmap? This might help people to make a timely decision to use aiemos or another shop system that already moved on to Symfony 6.

**Comment by aimeos** [comment]
This is planned for next year

**Comment by aimeos** [comment]
ETA 2022-04 / 2022-05 (~ 3 month from now)

**Comment by naek33** [comment]
ETA 2022-04 / 2022-05 (~ 3 month from now)   
To 
ETA 2023-04 / 2023-05 (~ 3 month from now)
:)

**Comment by arnaud-ritti** [comment]
Hi, did you have any update ?

**Comment by aimeos** [comment]
Yes, in the master branch there's currently the version for Symfony 6.3+ but it's not fully functional yet because we still struggle with the authentication stuff and are working on the assets. You can give it a try nevertheless and give feedback :-)

**Comment by aimeos** [comment]
There's an 2023.10 branch which is now working
